name: Deploy from Private Repo

on:
  push:
    branches:
      - site

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout public repository
      uses: actions/checkout@v3

    - name: Checkout private repository
      uses: actions/checkout@v3
      with:
        repository: Aravinth-Earth/simple-calculator
        token: ${{ secrets.GH_TOKEN }}
        path: private-repo

    - name: Copy files to folderB
      run: |
        mkdir -p public-repo/works/calculator
        cp private-repo/calc.html public-repo/works/calculator/calc.html

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Update calculator page from private repo"
        git push
